from enum import Enum

from client.ClientNetworkManager import ClientNetworkManager


class Message(Enum):
    SIGNIN = "SIGNIN"
    SIGNUP = "SIGNUP"
    DISCONNECTION = "DISCONNECTION"
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    # Store
    BUY = "BUY"
    GET_STORE = "GET_STORE"
    CHECK_ITEM = "CHECK_ITEM"
    CHECK_TRANSACTION_HISTORY = "CHECK_TRANSACTION_HISTORY"
    ACTIVATE_OBJECT = "ACTIVATE_OBJECT"
    # Profile
    GET_PROFILE = "GET_PROFILE"
    GET_POINT = "GET_POINT"  # In case we want to just display the points
    CHECK_RANKING = "CHECK_RANKING"
    # Course
    ADD_COURSE = "ADD_COURSE"
    DELETE_COURSE = "DELETE_COURSE"
    CHECK_COURSE = "CHECK_COURSE"
    GET_ALL_COURSES = "GET_ALL_COURSES"
    GET_USER_COURSES = "GET_USER_COURSES"
    GET_RESUME_OF_COURSE = "GET_RESUME_OF_COURSE"
    # Summary
    ADD_SUMMARY = "ADD_SUMMARY"
    READ_SUMMARY = "READ_SUMMARY"
    EDIT_SUMMARY = "EDIT_SUMMARY"
    DELETE_SUMMARY = "DELETE_SUMMARY"
    ADD_EVAL = "ADD_EVAL"
    CHECK_EVALUATIONS = "CHECK_EVALUATIONS"  # Not sure
    # Stats
    GET_LEADERBOARD = "GET_LEADERBOARD"
    GET_COURSES_MOST_RESUMES = "GET_COURSES_MOST_RESUMES"
    GET_RANKING_OBJECT = "GET_RANKING_OBJECT"
    GET_RES_IN_AT_LEAST_THREE_COURSES = "GET_RES_IN_AT_LEAST_THREE_COURSES"
    GET_RANKING_SPENDER = "GET_RANKING_SPENDER"
    GET_BEST_TEN_USERS = "GET_BEST_TEN_USERS"
    GET_SUMMARY_AVERAGE = "GET_SUMMARY_AVERAGE"


# Manager
mapping_actions = {
    Message.SIGNIN: ClientNetworkManager.signin,
    Message.SIGNUP: ClientNetworkManager.signup,
    Message.DISCONNECTION: ClientNetworkManager.disconnection,
}

# Handler
